# Auto-merge configuration for Dependabot PRs
# This file configures which dependency updates should be merged automatically.

# Configure here which dependency updates should be merged automatically.
# The recommended configuration is the following:
- match:
    # Merge patch updates for production dependencies
    dependency_type: production
    update_type: 'semver:patch'
- match:
    # Merge patch and minor updates for development dependencies
    dependency_type: development
    update_type: 'semver:minor'

# The syntax is based on the legacy dependabot v1 automerged_updates syntax, see:
# https://dependabot.com/docs/config-file/#automerged_updates

# IMPORTANT: Hierarchical matching applies:
# - semver:patch → only patch updates (e.g., 1.0.0 → 1.0.1)
# - semver:minor → patch AND minor updates (e.g., 1.0.0 → 1.0.1 or 1.0.0 → 1.1.0)
# - semver:major → patch, minor, AND major updates (all version changes)

# Additional examples:

# Allow all patch updates only (both production and development):
# - match:
#     update_type: 'semver:patch'

# Allow patch and minor updates for development dependencies:
# - match:
#     dependency_type: development
#     update_type: 'semver:minor'

# Allow all updates (patch, minor, and major) for development dependencies:
# - match:
#     dependency_type: development
#     update_type: 'semver:major'
